
version: 2

models:
  - name: ko_sales
    description: "KO products sales data"
    columns: 
      - name: subcat_id
        data_tests:
          - relationships:
              to: ref('dim_subcat')
              field: subcat_id
      - name: tm_brand_id
        data_tests:
          - relationships:
              to: ref('dim_tm')
              field: tm_brand_id
      - name: product_id
        data_tests:
          - relationships:
              to: ref('dim_tm')
              field: product_id
      - name: platform_id
        data_tests:
          - relationships:
              to: ref('dim_platform')
              field: id
      - name: day
        data_tests:
          - relationships:
              to: ref('dim_date')
              field: day
  - name: non_ko_sales
    description: "Non KO products sales data"
    columns: 
      - name: subcat_id
        data_tests:
          - relationships:
              to: ref('dim_subcat')
              field: subcat_id
      - name: platform_id
        data_tests:
          - relationships:
              to: ref('dim_platform')
              field: id
      - name: day
        data_tests:
          - relationships:
              to: ref('dim_date')
              field: day
