[project]
name = "etltools"
version = "0.0.1"
description = "ETL tools for brand perfomance report"
authors = [
    {name = "Maiara Souza"}
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "duckdb (>=1.1.3,<2.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)"
]