brand_performance:
  target: dev # this is the default target
  outputs:
    dev:
      type: duckdb
      path: '../performance_data_dev.db'
    prod:
      type: duckdb
      path: '../performance_data_prod.db'